# Welcome to Jekyll!

# Website settings
title: Thiago Meireles
description: PhD Candidate in Political Science at University of S達o Paulo
#keywords: Jack,Jalpc,blog,Jekyll,github,gh-pages
#baseurl:  /Jalpc # if you have suburl as homepage like '/homepage', please change it to '/homepage' and your repo's name should be 'homepage'
#url: https://jarrekk.github.io/Jalpc  # url should be 'http://<github_username>.github.io/homepage' as before
# url: http://127.0.0.1:4000
img_path: /Jalpc/static/assets/img/blog  # url should be '/homepage/static/assets/img/blog' as before

# author -- index page "about me" section
author:  # change following line to your infomation.
  name: Thiago Meireles  # Be used at blog posts' author.
  first_name: Thiago  # Be used at index page about me section.
  last_name: Meireles  # Be used at index page about me section.
  avatar: /static/assets/img/landing/avatar.jpg  # upload your avatar at directory and edit it.
  github_username: thiagomeireles  # Leave blank if you don't have now
  linkedin_id: thiago-de-oliveira-meireles-84605823 # Leave blank if you don't have now
  facebook_username: thiago.meireles.5 # Leave blank if you don't have now
  twitter_username: thiago_meireles  # Leave blank if you don't have now
  email: thiagomeireles@usp.br  # Leave blank if you don't have now
  cv: http://buscatextual.cnpq.br/buscatextual/visualizacv.do?id=K4433053P4 # An online CV can be printed as PDF, leave blank if you don't have now
  # skill icons are on avatar's left and right side. Reference urls are http://fontawesome.io/ and http://fizzed.com/oss/font-mfizz
  skill_icon1:
    - name: icon-apache
    - name: fa-linux
  skill_icon2:
    - name: fa-linux
    - name: icon-apache
  desc: I'm a PhD Candidate in Political Science at University of S達o Paulo. My research object is the internationalization processes of subnational governments in a comparative perspective, specifically on what leads them to develop these activiites. My research interests also include distributive conflicts and their impacts on inequality, as well as methodologies for causal inference. I have a master's degree in Political Science from the University of S達o Paulo (2016) and a bachelor's degree in International Relations from S達o Paulo State University (2012).  # Describe yourself.

# comment
disqus:  # if you wanna comment feature, go to https://disqus.com/ to get your configuration; if not, comment following two lines.
  name: jalpc

# analytics
## google analytics
ga:  # if you wanna this feature, go to https://www.google.com/analytics/ to get your configuration; if not, comment following line.
  id: UA-135403943-1

## google optimize
go:
  # id:

## growingIO
gio:  # if you wanna this feature, go to https://www.growingio.com/ to get your configuration; if not, comment following line.
  # id:

## donation
donation: off  # type 'on'/'off' to choice display donation button at post page or not

## carousels
index_carousel: on  # index page carousel switch
blog_carousel: on  # blog page carousel switch

# scss
sass:
  style: compressed

# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
